// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHB0t3wzrZ2qPu3pGH0Au9MnG-WNCdXcM',
    appId: '1:789276399680:web:bdf157f29274d6da85a7a5',
    messagingSenderId: '789276399680',
    projectId: 'fir-task-list-2344f',
    authDomain: 'fir-task-list-2344f.firebaseapp.com',
    storageBucket: 'fir-task-list-2344f.firebasestorage.app',
    measurementId: 'G-BHKDGHJ38V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ITY3YTkG8Euz3F_0wv8oC4Duy7swF44',
    appId: '1:789276399680:android:32ade85354eefd8c85a7a5',
    messagingSenderId: '789276399680',
    projectId: 'fir-task-list-2344f',
    storageBucket: 'fir-task-list-2344f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0waVF1Ant-ip6P_Ecbffh5_xPBFtKb0',
    appId: '1:789276399680:ios:165666694f57d81785a7a5',
    messagingSenderId: '789276399680',
    projectId: 'fir-task-list-2344f',
    storageBucket: 'fir-task-list-2344f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl0waVF1Ant-ip6P_Ecbffh5_xPBFtKb0',
    appId: '1:789276399680:ios:165666694f57d81785a7a5',
    messagingSenderId: '789276399680',
    projectId: 'fir-task-list-2344f',
    storageBucket: 'fir-task-list-2344f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHB0t3wzrZ2qPu3pGH0Au9MnG-WNCdXcM',
    appId: '1:789276399680:web:9213a06839efc96f85a7a5',
    messagingSenderId: '789276399680',
    projectId: 'fir-task-list-2344f',
    authDomain: 'fir-task-list-2344f.firebaseapp.com',
    storageBucket: 'fir-task-list-2344f.firebasestorage.app',
    measurementId: 'G-ECHN6WB2R8',
  );
}
